"""Small, explicit training utilities for bounded 4RC experiments."""

from .checkpoint import (
    load_temporal_tracking_checkpoint,
    read_temporal_patch_metadata,
    save_temporal_tracking_checkpoint,
)
from .diagnostics import (
    CONFIDENCE_DIAGNOSTICS_VERSION,
    DEFAULT_CONFIDENCE_TAU_MULTIPLES,
    DEFAULT_CONFIDENCE_TAUS,
    confidence_occlusion_diagnostics,
    reconstruction_shift_report,
    synchronized_consistency_stats,
    temporal_injection_report,
)
from .dumped_kubric import (
    DEPTH_SIDECAR_FLAG,
    DEPTH_SIDECAR_KEY,
    DEPTH_SIDECAR_NAME,
    DumpedKubricScene,
    ImageTransform,
    Observation,
    load_dumped_kubric_scene,
)
from .losses import (
    compose_tracking_loss,
    per_sample_huber_error,
    resolve_confidence_alpha,
    synchronized_consistency_loss,
    synchronized_pair_indices,
    track_confidence_loss,
    track_metric_error,
    track_position_loss,
)
from .sparse_tracking import (
    ELIGIBILITY_ASSIGNMENT_RULE,
    ELIGIBILITY_REJECTION_STAGES,
    ELIGIBILITY_ROLLUP_RULE,
    HELD_OUT_SPLIT_RULE,
    DetachedSim3,
    HeldOutSplit,
    SparseCorrespondences,
    SparseTrackingLossResult,
    build_anchor_correspondences,
    fit_scene_sim3,
    gather_at_correspondences,
    gather_query_anchor_points,
    reconstruction_drift_report,
    sparse_targets,
    sparse_tracking_loss,
    split_correspondences_by_region,
)

__all__ = [
    "CONFIDENCE_DIAGNOSTICS_VERSION",
    "DEFAULT_CONFIDENCE_TAUS",
    "DEFAULT_CONFIDENCE_TAU_MULTIPLES",
    "DEPTH_SIDECAR_FLAG",
    "DEPTH_SIDECAR_KEY",
    "DEPTH_SIDECAR_NAME",
    "ELIGIBILITY_ASSIGNMENT_RULE",
    "ELIGIBILITY_REJECTION_STAGES",
    "ELIGIBILITY_ROLLUP_RULE",
    "HELD_OUT_SPLIT_RULE",
    "DetachedSim3",
    "DumpedKubricScene",
    "HeldOutSplit",
    "ImageTransform",
    "Observation",
    "SparseCorrespondences",
    "SparseTrackingLossResult",
    "build_anchor_correspondences",
    "compose_tracking_loss",
    "confidence_occlusion_diagnostics",
    "fit_scene_sim3",
    "gather_at_correspondences",
    "gather_query_anchor_points",
    "load_temporal_tracking_checkpoint",
    "load_dumped_kubric_scene",
    "read_temporal_patch_metadata",
    "reconstruction_drift_report",
    "reconstruction_shift_report",
    "per_sample_huber_error",
    "resolve_confidence_alpha",
    "save_temporal_tracking_checkpoint",
    "sparse_targets",
    "sparse_tracking_loss",
    "split_correspondences_by_region",
    "synchronized_consistency_loss",
    "synchronized_consistency_stats",
    "synchronized_pair_indices",
    "temporal_injection_report",
    "track_confidence_loss",
    "track_metric_error",
    "track_position_loss",
]
